require: rubocop-performance

# Custom project config
AllCops:
  Exclude:
  - './Vagrantfile'
  - './vagrant-google.gemspec'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false